apiVersion: v1 
kind: Service
metadata: 
  name: cmmn-api-nodeport
spec: 
  ports: 
    - name: cmmn-api-port 
      port: 18080
      targetPort: 8080 
  selector: 
    app: cmmn-api
  type: NodePort