apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cmmn-api
spec:
  serviceName: cmmn-api-headless
  replicas: 1
  selector:
    matchLabels:
      app: cmmn-api
  template:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.kubernetes.io/node"
                operator: In
                values:
                  - "api"
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "node-role.kubernetes.io/node"
            labelSelector:
              matchExpressions:
                - key: node
                  operator: In
                  values:
                    - "api"
    metadata:
      labels:
        app: cmmn-api
    spec:
      setHostnameAsFQDN: true
      containers:
        - name: cmmn-api
          image: inquotient/cmmn-api:latest
          ports:
            - containerPort: 8080
              protocol: TCP 
          env:
            - name: DB_HOST
              value: "jdbc:mariadb://cmmn-mariadb-0.cmmn-mariadb-headless.dev.svc.cluster.local/cmmn"
            - name: DB_USERNAME
              value: "cmmn-api"
            - name: DB_PASSWORD
              value: "8HFWh9dz1H3Gv2JgtvGfV4hQlJC68yRpO2-pZX7E6jY="
      securityContext:
        runAsUser: 0
        runAsGroup: 0