apiVersion: v1
kind: Service
metadata:
  name: schema-reg-headless
  labels:
    app: schema-reg
spec:
  ports:
  - port: 8081
    name: schema-reg-port
  clusterIP: None
  selector:
    app: schema-reg