apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
data:
  postgresql_password: c+LsdtyGEiz0ir5U0WnDKwh4JOtClWZU
  # local을 trust로 설정하고 컨테이너 로딩이 되었을 때 해당 설정파일에서 peer로 변경해야함
  # local을 trust로 설정하지 않으면 postgres 계정 비밀번호가 설정되지 않음
  # 이걸로 미루어 짐작해본건데 postgres의 접근제어 정책은 종단간의 실제 ip로 접근제어가 이루어지는걸로 보임
  pghba-config: |
    host  keycloak  keycloak   .keycloak-headless.dev.svc.cluster.local md5
    host  gitlab  gitlab  .gitlab-headless.dev.svc.cluster.local md5
    host  all all 10.244.0.0/24 md5
    host  all all 10.96.0.0/16  md5
    # host  all all 0.0.0.0/0 md5
    # host  all all ::/0  md5
    # postgresql 초기화 후에 peer로 수정
    local all all trust
    host  all all 127.0.0.1/32  md5
    host  all all ::1/128 md5
    # host  keycloak  keycloak  0.0.0.0/0 md5