apiVersion: v1 
kind: Service
metadata: 
  name: postgresql-nodeport
spec: 
  ports: 
    - name: postgresql-port 
      port: 15432
      targetPort: 5432 
  selector: 
    app: postgresql 
  type: NodePort