apiVersion: v1 
kind: Service
metadata: 
  name: cmmn-mariadb-nodeport
spec: 
  ports: 
    - name: mariadb-port 
      port: 10306
      targetPort: 3306 
  selector: 
    app: cmmn-mariadb 
  type: NodePort