apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cmmn-mariadb
spec:
# whenDeleted를 Delete로 설정하면 pod가 지워지면 pvc도 같이 지워지도록 할 수 있다. 
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  serviceName: cmmn-mariadb-headless
  replicas: 1
  selector:
    matchLabels:
      app: cmmn-mariadb
  template:
    metadata:
      labels:
        app: cmmn-mariadb
    spec:
      setHostnameAsFQDN: true
      containers:
      - name: cmmn-mariadb
        image: bitnami/mariadb:11.0.2-debian-11-r0
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: cmmn-mariadb-configmap
              key: mysql_root_password
        volumeMounts:
        - name: mariadb-config
          mountPath: /etc/maysql/mariadb.cnf
          subPath: my.cnf
        - name: cmmn-mariadb-tde-volume
          mountPath: /mnt/tde
        - name: pvc
          mountPath: /bitnami/mariadb/data
          subPath: data
        - name: pvc
          mountPath: /opt/bitnami/mariadb/tmp
          subPath: tmp
        - name: pvc
          mountPath: /opt/bitnami/mariadb/logs
          subPath: logs
      volumes:
        - name: mariadb-config
          configMap:
            name: cmmn-mariadb-configmap
            items:
              - key: mariadb-config
                path: my.cnf
        - name: cmmn-mariadb-tde-volume
          hostPath:
            path: /home/ahnjisoo/mariadb/cmmn/tde
      securityContext:
        runAsUser: 0
        runAsGroup: 0
  volumeClaimTemplates:
    - metadata:
        name: pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 20Gi