apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  labels:
    app: zookeeper
spec:
  ports:
  - port: 2181
    name: zookeeper-client
  - port: 2888
    name: zookeeper-server
  - port: 3888
    name: zookeeper-leader-election
  clusterIP: None
  selector:
    app: zookeeper