apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-ui
spec:
# whenDeleted를 Delete로 설정하면 pod가 지워지면 pvc도 같이 지워지도록 할 수 있다. 
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.kubernetes.io/node"
                operator: In
                values:
                  - "kafka-ui"
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "node-role.kubernetes.io/node"
            labelSelector:
              matchExpressions:
                - key: node
                  operator: In
                  values:
                    - "kafka-ui"
    metadata:
      labels:
        app: kafka-ui
    spec:
      setHostnameAsFQDN: true
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
          - name: KAFKA_CLUSTERS_0_NAME
            value: "kafka"
          - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
            value: "kafka-headless.dev.svc.cluster.local:9092"
#          - name: KAFKA_CLUSTERS_0_METRICS_PORT
#            value: "9997"
          - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
            value: "http://schema-reg-headless.dev.svc.cluster.local:8081"
          - name: DYNAMIC_CONFIG_ENABLED
            value: "true"
#          volumeMounts:
#            - name: pvc
#              mountPath: /bitnami
#              subPath: bitnami    
      securityContext:
        runAsUser: 0
        runAsGroup: 0
#  volumeClaimTemplates:
#    - metadata:
#        name: pvc
#      spec:
#        accessModes:
#          - ReadWriteOnce
#        storageClassName: kops-csi-1-21
#        resources:
#          requests:
#            storage: 20Gi  