apiVersion: v1 
kind: Service
metadata: 
  name: keycloak-nodeport
spec: 
  ports: 
    - name: keycloak-http-port 
      port: 18083
      targetPort: 8080
    - name: keycloak-https-port
      port: 443
      targetPort: 8443
  selector: 
    app: keycloak
  type: NodePort