apiVersion: v1
kind: Service
metadata:
  name: keycloak-headless
  labels:
    app: keycloak
spec:
  ports:
  - port: 8080
    name: keycloak-port
  - port: 8443
    name: keycloak-secure-port
  clusterIP: None
  selector:
    app: keycloak