apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-configmap
data:
  gitlab-config: |
    external_url = "https://gitlab.oneinchmarket.co.kr"

    nginx['enable'] = false

    postgresql['enable'] = false
    postgresql['auto_restart_on_version_change'] = false

    geo_postgresql['auto_restart_on_version_change'] = false

    gitlab_rails['db_adapter'] = 'postgresql'
    gitlab_rails['db_encoding'] = 'utf8'
    gitlab_rails['db_host'] = 'postgresql-headless.dev.svc.cluster.local'
    gitlab_rails['db_port'] = 5432
    gitlab_rails['db_username'] = 'gitlab'
    gitlab_rails['db_password'] = 'HYKWk/iZlJg6EYt4L6XooTSI2ErjeU1f'

    # gitlab_rails['trusted_proxies'] = [ '100.64.0.0/10' ]

    puma['worker_processes'] = 0
    puma['listen'] = '0.0.0.0'
    puma['port'] = 9080
    puma['ssl_listen'] = '0.0.0.0'
    puma['ssl_port'] = 9443
    puma['ssl_certificate'] = '/etc/gitlab/tls/tls.crt'
    puma['ssl_certificate_key'] = '/etc/gitlab/tls/tls.key'

    puma['socket'] = ""

    gitlab_workhorse['listen_network'] = "tcp"
    gitlab_workhorse['listen_addr'] = "127.0.0.1:8181"

    web_server['external_users'] = ['nginx']

    letsencrypt['enable'] = false

    sidekiq['max_concurrency'] = 10

    prometheus_monitoring['enable'] = false

    gitlab_rails['env'] = {
      'MALLOC_CONF' => 'dirty_decay_ms:1000,muzzy_decay_ms:1000'
    }

    gitaly['env'] = {
      'MALLOC_CONF' => 'dirty_decay_ms:1000,muzzy_decay_ms:1000',
      'GITALY_COMMAND_SPAWN_MAX_PARALLEL' => '2'
    }