apiVersion: v1
kind: Service
metadata:
  name: gitlab-headless
  labels:
    app: gitlab
spec:
  ports:
  - port: 80
    name: gitlab-port
  - port: 443
    name: gitlab-secure-port
  clusterIP: None
  selector:
    app: gitlab