apiVersion: v1 
kind: Service
metadata: 
  name: gitlab-nodeport
spec: 
  ports: 
    - name: gitlab-web-port 
      port: 20080 
      targetPort: 80
    - name: gitlab-secure-port 
      port: 20443
      targetPort: 443 
  selector: 
    app: gitlab 
  type: NodePort