apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: kafka-listner
  - port: 9094
    name: kafka-internal
  clusterIP: None
  selector:
    app: kafka