apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: redis-port
  - port: 16379
    name: redis-cluster-port
  clusterIP: None
  selector:
    app: redis